# Note: Remove the baseurl in order to deploy at the domain root
title: Random Access Memories
# Whether the header (with large title and subtitle) should be displayed
header: false
subtitle: Blogspace for anything
author: Zeugnis
description: Blogspace for anything
show_author: true
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
# permalink: /blog/:categories/:year/:month/:day/:title.html
permalink: /blog/:categories/:slug
timezone: Asia/Seoul
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
plugins:
  - jekyll-feed
  - jekyll-sitemap